#!/usr/bin/env python3
"""Add remaining GPTK localization strings to Localizable.xcstrings."""

import re

xcstrings_path = '/Users/bdunwoodie/Documents/GitHub/Whisky/Whisky/Localizable.xcstrings'
with open(xcstrings_path, 'r') as f:
    content = f.read()

# Helper to create a localization entry block for one key with all languages
def make_entry(key, en_value):
    """Create a full localization entry block for one key."""
    langs = {
        "en": en_value,
        "zh-Hans": "",  # Will be filled below
        "zh-Hant": "",
        "ja": "",
        "ko": "",
        "de": "",
        "fr": "",
        "es": "",
        "it": "",
        "pt-BR": "",
        "pt-PT": "",
        "ru": "",
        "ar": "",
        "cs": "",
        "da": "",
        "fi": "",
        "nl": "",
        "pl": "",
        "ro": "",
        "tr": "",
        "uk": "",
        "vi": ""
    }
    
    # Provide reasonable translations for common strings
    trans = {
        "config.title.gptk": {"zh-Hans": "GPTK", "zh-Hant": "GPTK", "ja": "GPTK", "ko": "GPTK", 
                              "de": "GPTK", "fr": "GPTK", "es": "GPTK", "it": "GPTK", 
                              "pt-BR": "GPTK", "pt-PT": "GPTK", "ru": "GPTK", "ar": "GPTK",
                              "cs": "GPTK", "da": "GPTK", "fi": "GPTK", "nl": "GPTK",
                              "pl": "GPTK", "ro": "GPTK", "tr": "GPTK", "uk": "GPTK",
                              "vi": "GPTK"},
        "config.gptk": {"zh-Hans": "Game Porting Toolkit", "zh-Hant": "Game Porting Toolkit", 
                        "ja": "Game Porting Toolkit", "ko": "Game Porting Toolkit",
                        "de": "Game Porting Toolkit", "fr": "Game Porting Toolkit", 
                        "es": "Game Porting Toolkit", "it": "Game Porting Toolkit",
                        "pt-BR": "Game Porting Toolkit", "pt-PT": "Game Porting Toolkit",
                        "ru": "Game Porting Toolkit", "ar": "Game Porting Toolkit",
                        "cs": "Game Porting Toolkit", "da": "Game Porting Toolkit",
                        "fi": "Game Porting Toolkit", "nl": "Game Porting Toolkit",
                        "pl": "Game Porting Toolkit", "ro": "Game Porting Toolkit",
                        "tr": "Game Porting Toolkit", "uk": "Game Porting Toolkit",
                        "vi": "Game Porting Toolkit"},
        "config.gptk.checkUpdates": {"zh-Hans": "检查更新", "zh-Hant": "檢查更新", 
                                     "ja": "アップデートを確認", "ko": "업데이트 확인",
                                     "de": "Updates prüfen", "fr": "Vérifier les mises à jour",
                                     "es": "Buscar actualizaciones", "it": "Verifica aggiornamenti",
                                     "pt-BR": "Verificar atualizações", "pt-PT": "Verificar atualizações",
                                     "ru": "Проверить обновления", "ar": "التحقق من التحديثات",
                                     "cs": "Zkontrolovat aktualizace", "da": "Tjek for opdateringer",
                                     "fi": "Tarkista päivitykset", "nl": "Controleren op updates",
                                     "pl": "Sprawdź aktualizacje", "ro": "Verifică actualizările",
                                     "tr": "Güncellemeleri kontrol et", "uk": "Перевірити оновлення",
                                     "vi": "Kiểm tra cập nhật"},
        "config.gptk.found": {"zh-Hans": "检测到 GPTK", "zh-Hant": "偵測到 GPTK",
                              "ja": "GPTKを検出しました", "ko": "GPTK 감지됨",
                              "de": "GPTK erkannt", "fr": "GPTK détecté",
                              "es": "GPTK detectado", "it": "GPTK rilevato",
                              "pt-BR": "GPTK detectado", "pt-PT": "GPTK detetado",
                              "ru": "GPTK обнаружен", "ar": "تم اكتشاف GPTK",
                              "cs": "GPTK zjištěn", "da": "GPTK registreret",
                              "fi": "GPTK havaittu", "nl": "GPTK gedetecteerd",
                              "pl": "Wykryto GPTK", "ro": "GPTK detectat",
                              "tr": "GPTK algılandı", "uk": "GPTK виявлено",
                              "vi": "Đã phát hiện GPTK"},
        "config.gptk.notFound": {"zh-Hans": "未检测到 GPTK", "zh-Hant": "未偵測到 GPTK",
                                 "ja": "GPTKが見つかりません", "ko": "GPTK를 찾을 수 없음",
                                 "de": "GPTK nicht gefunden", "fr": "GPTK introuvable",
                                 "es": "GPTK no encontrado", "it": "GPTK non trovato",
                                 "pt-BR": "GPTK não encontrado", "pt-PT": "GPTK não encontrado",
                                 "ru": "GPTK не найден", "ar": "لم يتم العثور على GPTK",
                                 "cs": "GPTK nebyl nalezen", "da": "GPTK ikke fundet",
                                 "fi": "GPTK ei löydy", "nl": "GPTK niet gevonden",
                                 "pl": "Nie znaleziono GPTK", "ro": "GPTK nu a fost găsit",
                                 "tr": "GPTK bulunamadı", "uk": "GPTK не знайдено",
                                 "vi": "Không tìm thấy GPTK"},
        "config.gptk.version": {"zh-Hans": "版本: %@", "zh-Hant": "版本: %@",
                                "ja": "バージョン: %@" , "ko": "버전: %@",
                                "de": "Version: %@", "fr": "Version: %@",
                                "es": "Versión: %@", "it": "Versione: %@",
                                "pt-BR": "Versão: %@", "pt-PT": "Versão: %@",
                                "ru": "Версия: %@", "ar": "الإصدار: %@",
                                "cs": "Verze: %@", "da": "Version: %@",
                                "fi": "Versio: %@", "nl": "Versie: %@",
                                "pl": "Wersja: %@", "ro": "Versiune: %@",
                                "tr": "Sürüm: %@", "uk": "Версія: %@",
                                "vi": "Phiên bản: %@"},
        "config.gptk.update": {"zh-Hans": "更新 GPTK", "zh-Hant": "更新 GPTK",
                               "ja": "GPTK を更新", "ko": "GPTK 업데이트",
                               "de": "GPTK aktualisieren", "fr": "Mettre à jour GPTK",
                               "es": "Actualizar GPTK", "it": "Aggiorna GPTK",
                               "pt-BR": "Atualizar GPTK", "pt-PT": "Atualizar GPTK",
                               "ru": "Обновить GPTK", "ar": "تحديث GPTK",
                               "cs": "Aktualizovat GPTK", "da": "Opdater GPTK",
                               "fi": "Päivitä GPTK", "nl": "GPTK bijwerken",
                               "pl": "Aktualizuj GPTK", "ro": "Actualizează GPTK",
                               "tr": "GPTK'yi güncelle", "uk": "Оновити GPTK",
                               "vi": "Cập nhật GPTK"},
        "config.gptk.update.available": {"zh-Hans": "可用更新: %@", "zh-Hant": "可用更新: %@",
                                         "ja": "利用可能なアップデート: %@" , "ko": "사용 가능한 업데이트: %@",
                                         "de": "Update verfügbar: %@", "fr": "Mise à jour disponible: %@",
                                         "es": "Actualización disponible: %@", "it": "Aggiornamento disponibile: %@",
                                         "pt-BR": "Atualização disponível: %@", "pt-PT": "Atualização disponível: %@",
                                         "ru": "Доступно обновление: %@", "ar": "التحديث متاح: %@",
                                         "cs": "Aktualizace k dispozici: %@", "da": "Opdatering tilgængelig: %@",
                                         "fi": "Päivitys saatavilla: %@", "nl": "Update beschikbaar: %@",
                                         "pl": "Dostępna aktualizacja: %@", "ro": "Actualizare disponibilă: %@",
                                         "tr": "Güncelleme mevcut: %@", "uk": "Доступне оновлення: %@",
                                         "vi": "Cập nhật khả dụng: %@"},
        "config.gptk.update.current": {"zh-Hans": "已是最新: %@", "zh-Hant": "已是最新: %@",
                                       "ja": "最新: %@" , "ko": "최신 버전: %@",
                                       "de": "Aktuell: %@", "fr": "À jour: %@",
                                       "es": "Actualizado: %@", "it": "Aggiornato: %@",
                                       "pt-BR": "Atualizado: %@", "pt-PT": "Atualizado: %@",
                                       "ru": "Актуально: %@", "ar": "محدث: %@",
                                       "cs": "Aktuální: %@", "da": "Aktuel: %@",
                                       "fi": "Ajantasalla: %@", "nl": "Actueel: %@",
                                       "pl": "Aktualny: %@", "ro": "Actualizat: %@",
                                       "tr": "Güncel: %@", "uk": "Актуально: %@",
                                       "vi": "Cập nhật: %@"},
        "config.gptk.vkd3d": {"zh-Hans": "VKD3D", "zh-Hant": "VKD3D",
                              "ja": "VKD3D", "ko": "VKD3D",
                              "de": "VKD3D", "fr": "VKD3D",
                              "es": "VKD3D", "it": "VKD3D",
                              "pt-BR": "VKD3D", "pt-PT": "VKD3D",
                              "ru": "VKD3D", "ar": "VKD3D",
                              "cs": "VKD3D", "da": "VKD3D",
                              "fi": "VKD3D", "nl": "VKD3D",
                              "pl": "VKD3D", "ro": "VKD3D",
                              "tr": "VKD3D", "uk": "VKD3D",
                              "vi": "VKD3D"},
        "config.gptk.vkd3d.info": {"zh-Hans": "启用 VKD3D 以支持 D3D12",
                                   "zh-Hant": "啟用 VKD3D 以支援 D3D12",
                                   "ja": "D3D12 サポートのために VKD3D を有効化",
                                   "ko": "D3D12 지원을 위해 VKD3D 활성화",
                                   "de": "VKD3D für D3D12-Unterstützung aktivieren",
                                   "fr": "Activer VKD3D pour le support D3D12",
                                   "es": "Habilitar VKD3D para soporte D3D12",
                                   "it": "Abilita VKD3D per supporto D3D12",
                                   "pt-BR": "Habilitar VKD3D para suporte D3D12",
                                   "pt-PT": "Habilitar VKD3D para suporte D3D12",
                                   "ru": "Включить VKD3D для поддержки D3D12",
                                   "ar": "تمكين VKD3D لدعم D3D12",
                                   "cs": "Povolit VKD3D pro podporu D3D12",
                                   "da": "Aktivér VKD3D til D3D12-understøttelse",
                                   "fi": "Ota VKD3D käyttöön D3D12-tuen vuoksi",
                                   "nl": "VKD3D inschakelen voor D3D12-ondersteuning",
                                   "pl": "Włącz VKD3D dla obsługi D3D12",
                                   "ro": "Activați VKD3D pentru suport D3D12",
                                   "tr": "D3D12 desteği için VKD3D'yi etkinleştirin",
                                   "uk": "Увімкнути VKD3D для підтримки D3D12",
                                   "vi": "Bật VKD3D để hỗ trợ D3D12"},
        "config.gptk.vkd3d.debug.placeholder": {"zh-Hans": "vkd3d_debug,track_resource_refs",
                                                "zh-Hant": "vkd3d_debug,track_resource_refs",
                                                "ja": "vkd3d_debug,track_resource_refs",
                                                "ko": "vkd3d_debug,track_resource_refs",
                                                "de": "vkd3d_debug,track_resource_refs",
                                                "fr": "vkd3d_debug,track_resource_refs",
                                                "es": "vkd3d_debug,track_resource_refs",
                                                "it": "vkd3d_debug,track_resource_refs",
                                                "pt-BR": "vkd3d_debug,track_resource_refs",
                                                "pt-PT": "vkd3d_debug,track_resource_refs",
                                                "ru": "vkd3d_debug,track_resource_refs",
                                                "ar": "vkd3d_debug,track_resource_refs",
                                                "cs": "vkd3d_debug,track_resource_refs",
                                                "da": "vkd3d_debug,track_resource_refs",
                                                "fi": "vkd3d_debug,track_resource_refs",
                                                "nl": "vkd3d_debug,track_resource_refs",
                                                "pl": "vkd3d_debug,track_resource_refs",
                                                "ro": "vkd3d_debug,track_resource_refs",
                                                "tr": "vkd3d_debug,track_resource_refs",
                                                "uk": "vkd3d_debug,track_resource_refs",
                                                "vi": "vkd3d_debug,track_resource_refs"},
        "config.gptk.vkd3d.profile": {"zh-Hans": "VKD3D 配置文件",
                                      "zh-Hant": "VKD3D 設定檔",
                                      "ja": "VKD3D プロファイル",
                                      "ko": "VKD3D 프로필",
                                      "de": "VKD3D-Profil",
                                      "fr": "Profil VKD3D",
                                      "es": "Perfil VKD3D",
                                      "it": "Profilo VKD3D",
                                      "pt-BR": "Perfil VKD3D",
                                      "pt-PT": "Perfil VKD3D",
                                      "ru": "Профиль VKD3D",
                                      "ar": "ملف تعريف VKD3D",
                                      "cs": "Profil VKD3D",
                                      "da": "VKD3D-profil",
                                      "fi": "VKD3D-profiili",
                                      "nl": "VKD3D-profiel",
                                      "pl": "Profil VKD3D",
                                      "ro": "Profil VKD3D",
                                      "tr": "VKD3D Profili",
                                      "uk": "Профіль VKD3D",
                                      "vi": "Hồ sơ VKD3D"},
        "config.gptk.vkd3d.profile.auto": {"zh-Hans": "自动",
                                           "zh-Hant": "自動",
                                           "ja": "自動",
                                           "ko": "자동",
                                           "de": "Auto",
                                           "fr": "Auto",
                                           "es": "Auto",
                                           "it": "Auto",
                                           "pt-BR": "Auto",
                                           "pt-PT": "Auto",
                                           "ru": "Авто",
                                           "ar": "تلقائي",
                                           "cs": "Auto",
                                           "da": "Auto",
                                           "fi": "Automaattinen",
                                           "nl": "Auto",
                                           "pl": "Auto",
                                           "ro": "Auto",
                                           "tr": "Otomatik",
                                           "uk": "Авто",
                                           "vi": "Tự động"},
        "config.gptk.vkd3d.profile.zink": {"zh-Hans": "Zink",
                                           "zh-Hant": "Zink",
                                           "ja": "Zink",
                                           "ko": "Zink",
                                           "de": "Zink",
                                           "fr": "Zink",
                                           "es": "Zink",
                                           "it": "Zink",
                                           "pt-BR": "Zink",
                                           "pt-PT": "Zink",
                                           "ru": "Zink",
                                           "ar": "Zink",
                                           "cs": "Zink",
                                           "da": "Zink",
                                           "fi": "Zink",
                                           "nl": "Zink",
                                           "pl": "Zink",
                                           "ro": "Zink",
                                           "tr": "Zink",
                                           "uk": "Zink",
                                           "vi": "Zink"},
        "config.gptk.vkd3d.profile.radv": {"zh-Hans": "RADV",
                                           "zh-Hant": "RADV",
                                           "ja": "RADV",
                                           "ko": "RADV",
                                           "de": "RADV",
                                           "fr": "RADV",
                                           "es": "RADV",
                                           "it": "RADV",
                                           "pt-BR": "RADV",
                                           "pt-PT": "RADV",
                                           "ru": "RADV",
                                           "ar": "RADV",
                                           "cs": "RADV",
                                           "da": "RADV",
                                           "fi": "RADV",
                                           "nl": "RADV",
                                           "pl": "RADV",
                                           "ro": "RADV",
                                           "tr": "RADV",
                                           "uk": "RADV",
                                           "vi": "RADV"},
        "config.gptk.vkd3d.profile.custom": {"zh-Hans": "自定义",
                                             "zh-Hant": "自訂",
                                             "ja": "カスタム",
                                             "ko": "사용자 지정",
                                             "de": "Benutzerdefiniert",
                                             "fr": "Personnalisé",
                                             "es": "Personalizado",
                                             "it": "Personalizzato",
                                             "pt-BR": "Personalizado",
                                             "pt-PT": "Personalizado",
                                             "ru": "Пользовательский",
                                             "ar": "مخصص",
                                             "cs": "Vlastní",
                                             "da": "Brugerdefineret",
                                             "fi": "Mukautettu",
                                             "nl": "Aangepast",
                                             "pl": "Niestandardowy",
                                             "ro": "Personalizat",
                                             "tr": "Özel",
                                             "uk": "Користувацький",
                                             "vi": "Tùy chỉnh"},
        "config.gptk.shader.cache": {"zh-Hans": "着色器缓存",
                                     "zh-Hant": "著色器快取",
                                     "ja": "シェーダーキャッシュ",
                                     "ko": "셰이더 캐시",
                                     "de": "Shader-Cache",
                                     "fr": "Cache de shader",
                                     "es": "Caché de shader",
                                     "it": "Cache shader",
                                     "pt-BR": "Cache de shader",
                                     "pt-PT": "Cache de shader",
                                     "ru": "Кэш шейдеров",
                                     "ar": "مخزن المؤقت للشفرة المصدرة",
                                     "cs": "Cache shaderů",
                                     "da": "Shader-cache",
                                     "fi": "Shader-välimuisti",
                                     "nl": "Shader-cache",
                                     "pl": "Pamięć podręczna shaderów",
                                     "ro": "Cache shader",
                                     "tr": "Shader Önbelleği",
                                     "uk": "Кеш шейдерів",
                                     "vi": "Bộ nhớ đệm shader"},
        "config.gptk.shader.mode": {"zh-Hans": "着色器模式",
                                    "zh-Hant": "著色器模式",
                                    "ja": "シェーダーモード",
                                    "ko": "셰이더 모드",
                                    "de": "Shader-Modus",
                                    "fr": "Mode shader",
                                    "es": "Modo shader",
                                    "it": "Modalità shader",
                                    "pt-BR": "Modo shader",
                                    "pt-PT": "Modo shader",
                                    "ru": "Режим шейдера",
                                    "ar": "وضع الشفرة المصدرة",
                                    "cs": "Režim shaderu",
                                    "da": "Shader-tilstand",
                                    "fi": "Shader-tila",
                                    "nl": "Shader-modus",
                                    "pl": "Tryb shadera",
                                    "ro": "Mod shader",
                                    "tr": "Shader Modu",
                                    "uk": "Режим шейдера",
                                    "vi": "Chế độ shader"},
        "config.gptk.shader.mode.disabled": {"zh-Hans": "禁用",
                                             "zh-Hant": "停用",
                                             "ja": "無効",
                                             "ko": "사용 안 함",
                                             "de": "Deaktiviert",
                                             "fr": "Désactivé",
                                             "es": "Desactivado",
                                             "it": "Disabilitato",
                                             "pt-BR": "Desativado",
                                             "pt-PT": "Desativado",
                                             "ru": "Отключено",
                                             "ar": "معطل",
                                             "cs": "Zakázáno",
                                             "da": "Deaktiveret",
                                             "fi": "Poistettu käytöstä",
                                             "nl": "Uitgeschakeld",
                                             "pl": "Wyłączony",
                                             "ro": "Dezactivat",
                                             "tr": "Devre Dışı",
                                             "uk": "Вимкнено",
                                             "vi": "Đã tắt"},
        "config.gptk.shader.mode.compileOnLaunch": {"zh-Hans": "启动时编译",
                                                    "zh-Hant": "啟動時編譯",
                                                    "ja": "起動時にコンパイル",
                                                    "ko": "실행 시 컴파일",
                                                    "de": "Beim Start kompilieren",
                                                    "fr": "Compiler au lancement",
                                                    "es": "Compilar al iniciar",
                                                    "it": "Compila all'avvio",
                                                    "pt-BR": "Compilar ao iniciar",
                                                    "pt-PT": "Compilar ao iniciar",
                                                    "ru": "Компилировать при запуске",
                                                    "ar": "ترجمة عند التشغيل",
                                                    "cs": "Přeložit při spuštění",
                                                    "da": "Kompilér ved start",
                                                    "fi": "Käännä käynnistyksen yhteydessä",
                                                    "nl": "Compileren bij opstarten",
                                                    "pl": "Kompiluj przy uruchomieniu",
                                                    "ro": "Compilare la lansare",
                                                    "tr": "Başlatma Sırasında Derle",
                                                    "uk": "Компілювати при запуску",
                                                    "vi": "Biên dịch khi khởi chạy"},
        "config.gptk.shader.mode.prewarm": {"zh-Hans": "预热",
                                            "zh-Hant": "預熱",
                                            "ja": "プリウォーム",
                                            "ko": "프리워밍",
                                            "de": "Vorwärmen",
                                            "fr": "Préchauffage",
                                            "es": "Precalentamiento",
                                            "it": "Preriscaldamento",
                                            "pt-BR": "Pré-aquecimento",
                                            "pt-PT": "Pré-aquecimento",
                                            "ru": "Предварительный нагрев",
                                            "ar": "التسخين المسبق",
                                            "cs": "Předehřátí",
                                            "da": "Forvarmning",
                                            "fi": "Esilämmitys",
                                            "nl": "Voorverwarming",
                                            "pl": "Wstępne nagrzewanie",
                                            "ro": "Prelucrare",
                                            "tr": "Ön Isıtma",
                                            "uk": "Попереднє нагрівання",
                                            "vi": "Làm nóng trước"},
        "config.gptk.shader.progress": {"zh-Hans": "着色器编译进度",
                                        "zh-Hant": "著色器編譯進度",
                                        "ja": "シェーダーコンパイルの進捗",
                                        "ko": "셰이더 컴파일 진행률",
                                        "de": "Shader-Kompilierungsfortschritt",
                                        "fr": "Progression de la compilation des shaders",
                                        "es": "Progreso de compilación de shaders",
                                        "it": "Progresso compilazione shader",
                                        "pt-BR": "Progresso da compilação do shader",
                                        "pt-PT": "Progresso da compilação do shader",
                                        "ru": "Прогресс компиляции шейдеров",
                                        "ar": "تقدم ترجمة الشفرة المصدرة",
                                        "cs": "Průběh kompilace shaderu",
                                        "da": "Fremgang for shader-kompilering",
                                        "fi": "Shader-käännöksen edistyminen",
                                        "nl": "Voortgang shader-compilatie",
                                        "pl": "Postęp kompilacji shadera",
                                        "ro": "Progres compilare shader",
                                        "tr": "Shader Derleme İlerlemesi",
                                        "uk": "Прогрес компіляції шейдера",
                                        "vi": "Tiến trình biên dịch shader"},
        "config.gptk.shader.error.unknown": {"zh-Hans": "着色器编译期间发生未知错误",
                                             "zh-Hant": "著色器編譯期間發生未知錯誤",
                                             "ja": "シェーダーコンパイル中に不明なエラーが発生しました",
                                             "ko": "셰이더 컴파일 중 알 수 없는 오류 발생",
                                             "de": "Unbekannter Fehler während der Shader-Kompilierung aufgetreten",
                                             "fr": "Une erreur inconnue s'est produite lors de la compilation des shaders",
                                             "es": "Se produjo un error desconocido durante la compilación del shader",
                                             "it": "Si è verificato un errore sconosciuto durante la compilazione dello shader",
                                             "pt-BR": "Ocorreu um erro desconhecido durante a compilação do shader",
                                             "pt-PT": "Ocorreu um erro desconhecido durante a compilação do shader",
                                             "ru": "Произошла неизвестная ошибка во время компиляции шейдера",
                                             "ar": "حدث خطأ غير معروف أثناء ترجمة الشفرة المصدرة",
                                             "cs": "Během kompilace shaderu došlo k neznámé chybě",
                                             "da": "Der opstod en ukendt fejl under shader-kompilering",
                                             "fi": "Tuntematon virhe shader-käännöksessä",
                                             "nl": "Onbekende fout opgetreden tijdens shader-compilatie",
                                             "pl": "Wystąpił nieznany błąd podczas kompilacji shadera",
                                             "ro": "A apărut o eroare necunoscută în timpul compilării shaderului",
                                             "tr": "Shader derleme sırasında bilinmeyen bir hata oluştu",
                                             "uk": "Виникла невідома помилка під час компіляції шейдера",
                                             "vi": "Đã xảy ra lỗi không xác định trong quá trình biên dịch shader"},
        "config.gptk.shader.complete": {"zh-Hans": "着色器编译完成",
                                        "zh-Hant": "著色器編譯完成",
                                        "ja": "シェーダーコンパイル完了",
                                        "ko": "셰이더 컴파일 완료",
                                        "de": "Shader-Kompilierung abgeschlossen",
                                        "fr": "Compilation des shaders terminée",
                                        "es": "Compilación de shaders completada",
                                        "it": "Compilazione shader completata",
                                        "pt-BR": "Compilação do shader concluída",
                                        "pt-PT": "Compilação do shader concluída",
                                        "ru": "Компиляция шейдеров завершена",
                                        "ar": "اكتملت ترجمة الشفرة المصدرة",
                                        "cs": "Kompilace shaderu dokončena",
                                        "da": "Shader-kompilering fuldført",
                                        "fi": "Shader-käännös valmis",
                                        "nl": "Shader-compilatie voltooid",
                                        "pl": "Kompilacja shadera ukończona",
                                        "ro": "Compilarea shaderului completată",
                                        "tr": "Shader derlemesi tamamlandı",
                                        "uk": "Компіляцію шейдера завершено",
                                        "vi": "Biên dịch shader hoàn tất"},
        "config.gptk.perf.mode": {"zh-Hans": "性能模式",
                                  "zh-Hant": "效能模式",
                                  "ja": "パフォーマンスモード",
                                  "ko": "성능 모드",
                                  "de": "Leistungsmodus",
                                  "fr": "Mode performance",
                                  "es": "Modo de rendimiento",
                                  "it": "Modalità prestazioni",
                                  "pt-BR": "Modo de desempenho",
                                  "pt-PT": "Modo de desempenho",
                                  "ru": "Режим производительности",
                                  "ar": "وضع الأداء",
                                  "cs": "Režim výkonu",
                                  "da": "Ydelsestilstand",
                                  "fi": "Suorituskykytila",
                                  "nl": "Prestatiemodus",
                                  "pl": "Tryb wydajności",
                                  "ro": "Mod performanță",
                                  "tr": "Performans Modu",
                                  "uk": "Режим продуктивності",
                                  "vi": "Chế độ hiệu suất"},
        "config.gptk.perf.mode.balanced": {"zh-Hans": "平衡",
                                           "zh-Hant": "平衡",
                                           "ja": "バランス",
                                           "ko": "균형",
                                           "de": "Ausgewogen",
                                           "fr": "Équilibré",
                                           "es": "Equilibrado",
                                           "it": "Bilanciato",
                                           "pt-BR": "Equilibrado",
                                           "pt-PT": "Equilibrado",
                                           "ru": "Сбалансированный",
                                           "ar": "متوازن",
                                           "cs": "Vyvážený",
                                           "da": "Balanceret",
                                           "fi": "Tasapainoinen",
                                           "nl": "Gebalanceerd",
                                           "pl": "Zbalansowany",
                                           "ro": "Echilibrat",
                                           "tr": "Dengeli",
                                           "uk": "Збалансований",
                                           "vi": "Cân bằng"},
        "config.gptk.perf.mode.performance": {"zh-Hans": "性能",
                                              "zh-Hant": "效能",
                                              "ja": "パフォーマンス",
                                              "ko": "성능",
                                              "de": "Leistung",
                                              "fr": "Performance",
                                              "es": "Rendimiento",
                                              "it": "Prestazioni",
                                              "pt-BR": "Desempenho",
                                              "pt-PT": "Desempenho",
                                              "ru": "Производительность",
                                              "ar": "الأداء",
                                              "cs": "Výkon",
                                              "da": "Ydelse",
                                              "fi": "Suorituskyky",
                                              "nl": "Prestatie",
                                              "pl": "Wydajność",
                                              "ro": "Performanță",
                                              "tr": "Performans",
                                              "uk": "Продуктивність",
                                              "vi": "Hiệu suất"},
        "config.gptk.perf.mode.quality": {"zh-Hans": "质量",
                                          "zh-Hant": "品質",
                                          "ja": "品質",
                                          "ko": "품질",
                                          "de": "Qualität",
                                          "fr": "Qualité",
                                          "es": "Calidad",
                                          "it": "Qualità",
                                          "pt-BR": "Qualidade",
                                          "pt-PT": "Qualidade",
                                          "ru": "Качество",
                                          "ar": "الجودة",
                                          "cs": "Kvalita",
                                          "da": "Kvalitet",
                                          "fi": "Laatu",
                                          "nl": "Kwaliteit",
                                          "pl": "Jakość",
                                          "ro": "Calitate",
                                          "tr": "Kalite",
                                          "uk": "Якість",
                                          "vi": "Chất lượng"},
        "config.gptk.memory.mode": {"zh-Hans": "内存模式",
                                    "zh-Hant": "記憶體模式",
                                    "ja": "メモリモード",
                                    "ko": "메모리 모드",
                                    "de": "Speichermodus",
                                    "fr": "Mode mémoire",
                                    "es": "Modo de memoria",
                                    "it": "Modalità memoria",
                                    "pt-BR": "Modo de memória",
                                    "pt-PT": "Modo de memória",
                                    "ru": "Режим памяти",
                                    "ar": "وضع الذاكرة",
                                    "cs": "Režim paměti",
                                    "da": "Hukommelsestilstand",
                                    "fi": "Muistitila",
                                    "nl": "Geheugenmodus",
                                    "pl": "Tryb pamięci",
                                    "ro": "Mod memorie",
                                    "tr": "Bellek Modu",
                                    "uk": "Режим пам'яті",
                                    "vi": "Chế độ bộ nhớ"},
        "config.gptk.memory.mode.auto": {"zh-Hans": "自动",
                                         "zh-Hant": "自動",
                                         "ja": "自動",
                                         "ko": "자동",
                                         "de": "Auto",
                                         "fr": "Auto",
                                         "es": "Auto",
                                         "it": "Auto",
                                         "pt-BR": "Auto",
                                         "pt-PT": "Auto",
                                         "ru": "Авто",
                                         "ar": "تلقائي",
                                         "cs": "Auto",
                                         "da": "Auto",
                                         "fi": "Automaattinen",
                                         "nl": "Auto",
                                         "pl": "Auto",
                                         "ro": "Auto",
                                         "tr": "Otomatik",
                                         "uk": "Авто",
                                         "vi": "Tự động"},
        "config.gptk.memory.mode.limited": {"zh-Hans": "限制",
                                            "zh-Hant": "限制",
                                            "ja": "制限",
                                            "ko": "제한",
                                            "de": "Begrenzt",
                                            "fr": "Limité",
                                            "es": "Limitado",
                                            "it": "Limitato",
                                            "pt-BR": "Limitado",
                                            "pt-PT": "Limitado",
                                            "ru": "Ограниченный",
                                            "ar": "محدود",
                                            "cs": "Omezený",
                                            "da": "Begrænset",
                                            "fi": "Rajoitettu",
                                            "nl": "Beperkt",
                                            "pl": "Ograniczony",
                                            "ro": "Limitat",
                                            "tr": "Sınırlı",
                                            "uk": "Обмежений",
                                            "vi": "Giới hạn"},
        "config.gptk.memory.limit": {"zh-Hans": "内存限制 (MB)",
                                     "zh-Hant": "記憶體限制 (MB)",
                                     "ja": "メモリ制限 (MB)",
                                     "ko": "메모리 제한 (MB)",
                                     "de": "Speicherlimit (MB)",
                                     "fr": "Limite de mémoire (Mo)",
                                     "es": "Límite de memoria (MB)",
                                     "it": "Limite di memoria (MB)",
                                     "pt-BR": "Limite de memória (MB)",
                                     "pt-PT": "Limite de memória (MB)",
                                     "ru": "Лимит памяти (МБ)",
                                     "ar": "حد الذاكرة (ميجابايت)",
                                     "cs": "Limit paměti (MB)",
                                     "da": "Hukommelsesgrænse (MB)",
                                     "fi": "Muistiraja (MB)",
                                     "nl": "Geheugenlimiet (MB)",
                                     "pl": "Limit pamięci (MB)",
                                     "ro": "Limită memorie (MB)",
                                     "tr": "Bellek Limiti (MB)",
                                     "uk": "Ліміт пам'яті (МБ)",
                                     "vi": "Giới hạn bộ nhớ (MB)"},
    }
    
    # Build the entry block
    lines = [f'    "{key}" : {{']
    lines.append('      "localizations" : {')
    
    lang_list = list(langs.keys())
    for i, lang in enumerate(lang_list):
        value = trans.get(key, {}).get(lang, langs[lang]) or en_value  # fallback to English
        lines.append(f'        "{lang}" : {{')
        lines.append('          "stringUnit" : {')
        lines.append('            "state" : "translated",')
        lines.append(f'            "value" : "{value}"')
        lines.append('          }')
        lines.append('        },')
    
    # Remove trailing comma from last language
    lines[-1] = lines[-1].rstrip(',')
    
    lines.append('      }')
    lines.append('    },')
    
    return '\n'.join(lines)

# Define all GPTK keys that need entries (from the code grep output)
keys_to_add = [
    ("config.title.gptk", "GPTK"),
    ("config.gptk", "Game Porting Toolkit"),
    ("config.gptk.checkUpdates", "Check for Updates"),
    # Already added: config.gptk.found, config.gptk.notFound
    ("config.gptk.version", "Version: %@"),
    ("config.gptk.update", "Update GPTK"),
    ("config.gptk.update.available", "Update available: %@"),
    ("config.gptk.update.current", "Up to date: %@"),
    ("config.gptk.vkd3d", "VKD3D"),
    ("config.gptk.vkd3d.info", "Enable VKD3D for D3D12 support"),
    ("config.gptk.vkd3d.debug.placeholder", "vkd3d_debug,track_resource_refs"),
    ("config.gptk.vkd3d.profile", "VKD3D Profile"),
    ("config.gptk.vkd3d.profile.auto", "Auto"),
    ("config.gptk.vkd3d.profile.zink", "Zink"),
    ("config.gptk.vkd3d.profile.radv", "RADV"),
    ("config.gptk.vkd3d.profile.custom", "Custom"),
    ("config.gptk.shader.cache", "Shader Cache"),
    ("config.gptk.shader.mode", "Shader Mode"),
    ("config.gptk.shader.mode.disabled", "Disabled"),
    ("config.gptk.shader.mode.compileOnLaunch", "Compile on Launch"),
    ("config.gptk.shader.mode.prewarm", "Prewarm"),
    ("config.gptk.shader.progress", "Shader Compilation Progress"),
    ("config.gptk.shader.error.unknown", "Unknown error occurred during shader compilation"),
    ("config.gptk.shader.complete", "Shader compilation complete"),
    ("config.gptk.perf.mode", "Performance Mode"),
    ("config.gptk.perf.mode.balanced", "Balanced"),
    ("config.gptk.perf.mode.performance", "Performance"),
    ("config.gptk.perf.mode.quality", "Quality"),
    ("config.gptk.memory.mode", "Memory Mode"),
    ("config.gptk.memory.mode.auto", "Auto"),
    ("config.gptk.memory.mode.limited", "Limited"),
    ("config.gptk.memory.limit", "Memory Limit (MB)"),
]

# Build all entries
all_entries = []
for key, en_value in keys_to_add:
    entry = make_entry(key, en_value)
    all_entries.append(entry)

# Join with newlines between entries
combined = '\n'.join(all_entries)

# Find insertion point - right before "config.enhacnedSync.esync"
insertion_marker = '    "config.enhacnedSync.esync"'
if insertion_marker in content:
    # Insert all GPTK strings before this marker
    new_content = content.replace(insertion_marker, combined + '\n' + insertion_marker)
    
    # Write the modified content back to the file
    with open(xcstrings_path, 'w') as f:
        f.write(new_content)
    
    print(f"Added {len(keys_to_add)} GPTK localization strings successfully!")
else:
    print(f"Could not find insertion marker: {insertion_marker}")
